version: "2.2"
services:
   nginx:
       container_name: "nginx-portfolio"
       image: nginx:latest
       volumes:
          - ./conf.d:/etc/nginx/conf.d
          - ./build:/usr/share/nginx/html
       ports:
          - "8081:80"
       environment:
          - NGINX_HOST=portfolio.greenjtee.com
          - NGINX_PORT=80
       restart: unless-stopped
